server:
  port: 8001
  servlet:
    context-path: /xiongdi-admin
  tomcat:
#    最大线程
    max-threads: 1000
#    最小保留线程
    min-spare-threads: 30
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true
  freemarker:
    suffix: .html
    request-context-attribute: request

# mybatis plus的配置
mybatis-plus:
  # mybatis 的原生配置
  configuration:
    cache-enabled: false # 是否开启缓存
    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则（camel case）映射
    call-setters-on-nulls: true # MyBatis 在使用 resultMap 来映射查询结果中的列，如果查询结果中包含空值的列
    jdbc-type-for-null: 'null' # 如果type为空
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # MyBatis-Plus 全局策略配置
  global-config:
    # MyBatis-Plus 全局策略中的 DB 策略配置
    db-config:
      id-type: auto # 全局默认主键类型，AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      field-strategy: not_null # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      logic-delete-value: -1 # 逻辑已删除值,(逻辑删除下有)
      logic-not-delete-value: 0 # 逻辑未删除值,(逻辑删除下有效)
    banner: false # 是否显示mybatis-plus的图标
    # XML 映射路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体别名包映射路径，多个包用逗号隔开
  type-aliases-package: io.xiongdi.modules.*.entity

xd:
  cluster: false  #集群配置  true集群环境   false单机环境，还需打开pom.xml里的spring-session-data-redis注释
  globalSessionTimeout: 3600   #单机环境，session过期时间为60分钟
  redis:
    open: false  #是否开启redis缓存  true开启   false关闭